//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotAPI_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_categoria
    {
        public int id_usuario_categoria { get; set; }
        public int id_usuario { get; set; }
        public int id_categoria { get; set; }
        public int isPrimary { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual users users { get; set; }
    }
}
