//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotApi0.Models
{
    using System;
    
    public class comentariosModel
    {

        public int id_comentario { get; set; }
        public int id_user { get; set; }
        public int id_post { get; set; }
        public string contenido { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<bool> isDeleted { get; set; }

    }
}
