//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotApi0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class like_comentario
    {
        public int id_like_comentario { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> comentario_id { get; set; }
    }
}
