//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotApi0.Models
{
    using System;

    public class publicacion_guardadasModel
    {
        public int id_publicacion_guardada { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_post { get; set; }
        public System.DateTime fecha { get; set; }

    }
}
