//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotApi0.Models
{
    using System;
    
    public class seguidoresModel
    {
        public int id_seguidores { get; set; }
        public int seguidor_id { get; set; }
        public int id_seguido { get; set; }
        public Nullable<bool> accepted { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }


    }
}
