//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotApi0.Models
{
    using System;
    using System.Collections.Generic;

    public partial class userModel
    {
        public int id_user { get; set; }
        public string username { get; set; }
        public string img { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string descripcion { get; set; }
        public string pass { get; set; }
        public bool? isVendor { get; set; }
        public int? puntaje { get; set; }
        public string email { get; set; }
        public float? xlat { get; set; }
        public float? ylon { get; set; }
        public short? isActive { get; set; }
        public string dui { get; set; }
        public string num_telefono { get; set; }

    }
}
