//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brot.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Publicacion
    {
        public Publicacion()
        {
            this.Comentarios = new HashSet<Comentario>();
            this.interaccion_post = new HashSet<Interaccion_post>();
            this.Likes_post = new HashSet<Like_post>();
            this.Publicacion_Guardadas = new HashSet<Publicacion_guardada>();
        }
        [Key]
        public int id_post { get; set; }
        public int id_user { get; set; }
        public string img { get; set; }
        public Nullable<bool> isImg { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public int CantVisitasPublicacion { get; set; }

        //TODO: medium -  Change classes for use this Models with CUSTOM NOT MAPPED attributes
        [NotMapped]
        public int CantLikes { get; set; }
        [NotMapped]
        public int CantComentarios { get; set; }



        public virtual ICollection<Comentario> Comentarios { get; set; }
        public virtual ICollection<Interaccion_post> interaccion_post { get; set; }
        public virtual ICollection<Like_post> Likes_post { get; set; }
        public virtual ICollection<Publicacion_guardada> Publicacion_Guardadas { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
