

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BrotAPI_Final.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

    //SomeeDBBrotEntities
public partial class DB_BrotEntitiesLast : DbContext
{
    public DB_BrotEntitiesLast()
        : base("name=DB_BrotEntitiesLast")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<comentarios> comentarios { get; set; }

    public virtual DbSet<interaccion_post> interaccion_post { get; set; }

    public virtual DbSet<like_comentario> like_comentario { get; set; }

    public virtual DbSet<like_post> like_post { get; set; }

    public virtual DbSet<publicacion_guardada> publicacion_guardada { get; set; }

    public virtual DbSet<publicaciones> publicaciones { get; set; }

    public virtual DbSet<seguidores> seguidores { get; set; }

    public virtual DbSet<users> users { get; set; }

    public virtual DbSet<visita_busqueda> visita_busqueda { get; set; }

    public virtual DbSet<visita_pefil_post> visita_pefil_post { get; set; }

}

}

